import { Helmet } from "react-helmet-async";

const Disclaimer = () => (
  <>
    <Helmet>
      <title>Disclaimer | IP Protection India</title>
      <meta name="description" content="Legal disclaimer for IP Protection India website and services." />
    </Helmet>
    <section className="py-20 md:py-28">
      <div className="container mx-auto max-w-3xl px-4">
        <h1 className="mb-8 font-serif text-4xl font-bold">Disclaimer</h1>
        <div className="prose prose-sm text-muted-foreground space-y-4">
          <p>
            The information provided on this website is for general informational purposes only. All information on the site is provided in good faith; however, we make no representation or warranty of any kind, express or implied, regarding the accuracy, adequacy, validity, reliability, availability, or completeness of any information on the site.
          </p>
          <h2 className="font-serif text-xl font-bold text-foreground">No Legal Advice</h2>
          <p>
            The content on this website does not constitute legal advice. The use of this website does not create an attorney-client relationship between you and Advocate Anuradha R. Kulkarni or IP Protection India. For specific legal advice regarding your individual situation, please schedule a consultation.
          </p>
          <h2 className="font-serif text-xl font-bold text-foreground">AI Tools Disclaimer</h2>
          <p>
            The AI-powered tools available on this website (Brand Name Generator, Trademark Risk Analyzer, Objection Reply Generator, etc.) are provided for reference and educational purposes only. The results generated by these tools should not be considered as legal opinions or professional advice. Always consult a qualified trademark attorney before making legal decisions.
          </p>
          <h2 className="font-serif text-xl font-bold text-foreground">No Guarantee of Results</h2>
          <p>
            Past results are not a guarantee of future outcomes. Every legal matter is unique, and the outcome of any case depends on its specific facts and circumstances. Success rates mentioned on this website are based on historical data and may not be indicative of future performance.
          </p>
          <h2 className="font-serif text-xl font-bold text-foreground">External Links</h2>
          <p>
            This website may contain links to external websites, including the IP India government portal. We do not control and are not responsible for the content or practices of any third-party websites.
          </p>
          <p className="text-xs mt-8">Last updated: {new Date().toLocaleDateString("en-IN", { year: "numeric", month: "long" })}</p>
        </div>
      </div>
    </section>
  </>
);

export default Disclaimer;