import Layout from "@/components/Layout";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { useState } from "react";
import { FileText, Download, Loader2 } from "lucide-react";

const trademarkClasses = [
  "Class 9 - Electronics", "Class 25 - Clothing", "Class 35 - Advertising & Business",
  "Class 42 - IT & Software Services", "Class 43 - Restaurant & Hotels",
];

type DocForm = {
  name: string;
  address: string;
  brand: string;
  tmClass: string;
  businessType: string;
};

const DocumentGenerator = () => {
  const [form, setForm] = useState<DocForm>({ name: "", address: "", brand: "", tmClass: "", businessType: "" });
  const [generated, setGenerated] = useState(false);
  const [loading, setLoading] = useState(false);

  const handleGenerate = (e: React.FormEvent) => {
    e.preventDefault();
    if (!form.name || !form.brand) return;
    setLoading(true);
    setTimeout(() => {
      setGenerated(true);
      setLoading(false);
    }, 1000);
  };

  const handleDownload = () => {
    const text = `
TRADEMARK APPLICATION — FORM TM-A
===================================

To: The Registrar of Trade Marks
    Controller General of Patents, Designs & Trade Marks

Application for registration of a Trade Mark under the Trade Marks Act, 1999

APPLICANT DETAILS
─────────────────
Applicant Name:    ${form.name}
Address:           ${form.address}
Business Type:     ${form.businessType}

TRADEMARK DETAILS
──────────────────
Trademark:         ${form.brand}
Class:             ${form.tmClass}

DECLARATION
───────────
I/We hereby declare that:

1. The above trademark is being used or proposed to be used by me/us 
   in respect of the goods/services mentioned above.

2. I/We claim to be the proprietor(s) of the said trademark.

3. The information provided in this application is true and correct 
   to the best of my/our knowledge and belief.

4. No other entity, to the best of my/our knowledge, has the right 
   to use the said trademark.


Signature: _________________________

Date: ${new Date().toLocaleDateString("en-IN")}

Place: _________________________


Note: This is a draft document generated for reference purposes. 
The actual Form TM-A must be filed through the official IP India portal.
===================================
Generated by IP Protection India
    `.trim();

    const blob = new Blob([text], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `TM-A_Draft_${form.brand.replace(/\s+/g, "_")}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <Layout>
      <section className="py-20 md:py-28">
        <div className="container mx-auto px-4">
          <div className="mx-auto max-w-3xl text-center">
            <FileText className="mx-auto mb-4 h-12 w-12 text-primary" />
            <h1 className="mb-4 font-serif text-4xl font-bold md:text-5xl">
              Legal Document Generator
            </h1>
            <p className="text-lg text-muted-foreground">
              Auto-generate trademark application drafts (Form TM-A) from your details.
            </p>
          </div>
        </div>
      </section>

      <section className="pb-20">
        <div className="container mx-auto max-w-2xl px-4">
          {!generated ? (
            <form onSubmit={handleGenerate} className="space-y-4 rounded-lg border border-border bg-card p-6">
              <div>
                <label className="mb-1.5 block text-sm font-medium">Applicant Name *</label>
                <Input value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} placeholder="Full legal name" />
              </div>
              <div>
                <label className="mb-1.5 block text-sm font-medium">Address *</label>
                <Textarea value={form.address} onChange={(e) => setForm({ ...form, address: e.target.value })} placeholder="Full address" rows={3} />
              </div>
              <div>
                <label className="mb-1.5 block text-sm font-medium">Brand Name *</label>
                <Input value={form.brand} onChange={(e) => setForm({ ...form, brand: e.target.value })} placeholder="Trademark to register" />
              </div>
              <div>
                <label className="mb-1.5 block text-sm font-medium">Trademark Class</label>
                <Select value={form.tmClass} onValueChange={(v) => setForm({ ...form, tmClass: v })}>
                  <SelectTrigger><SelectValue placeholder="Select class" /></SelectTrigger>
                  <SelectContent>
                    {trademarkClasses.map((c) => <SelectItem key={c} value={c}>{c}</SelectItem>)}
                  </SelectContent>
                </Select>
              </div>
              <div>
                <label className="mb-1.5 block text-sm font-medium">Business Type</label>
                <Select value={form.businessType} onValueChange={(v) => setForm({ ...form, businessType: v })}>
                  <SelectTrigger><SelectValue placeholder="Select type" /></SelectTrigger>
                  <SelectContent>
                    <SelectItem value="Sole Proprietorship">Sole Proprietorship</SelectItem>
                    <SelectItem value="Partnership">Partnership</SelectItem>
                    <SelectItem value="LLP">LLP</SelectItem>
                    <SelectItem value="Private Limited">Private Limited</SelectItem>
                    <SelectItem value="Individual">Individual</SelectItem>
                  </SelectContent>
                </Select>
              </div>
              <Button variant="gold" type="submit" className="w-full" disabled={loading || !form.name || !form.brand}>
                {loading ? <Loader2 className="mr-2 h-4 w-4 animate-spin" /> : <FileText className="mr-2 h-4 w-4" />}
                {loading ? "Generating..." : "Generate Document"}
              </Button>
            </form>
          ) : (
            <div className="space-y-6">
              <div className="rounded-lg border border-border bg-card p-6">
                <h2 className="mb-4 font-serif text-lg font-bold">Document Preview — Form TM-A Draft</h2>
                <div className="space-y-3 rounded-md bg-secondary p-4 font-mono text-sm">
                  <p><span className="text-muted-foreground">Applicant:</span> {form.name}</p>
                  <p><span className="text-muted-foreground">Address:</span> {form.address}</p>
                  <p><span className="text-muted-foreground">Trademark:</span> <span className="font-bold text-primary">{form.brand}</span></p>
                  <p><span className="text-muted-foreground">Class:</span> {form.tmClass || "Not specified"}</p>
                  <p><span className="text-muted-foreground">Business Type:</span> {form.businessType || "Not specified"}</p>
                  <hr className="border-border my-2" />
                  <p className="text-muted-foreground italic">
                    I hereby declare that the above information is true and correct to the best of my knowledge.
                  </p>
                  <p><span className="text-muted-foreground">Date:</span> {new Date().toLocaleDateString("en-IN")}</p>
                </div>
              </div>
              <div className="flex gap-3">
                <Button variant="gold" className="flex-1" onClick={handleDownload}>
                  <Download className="mr-2 h-4 w-4" /> Download Document
                </Button>
                <Button variant="gold-outline" className="flex-1" onClick={() => { setGenerated(false); setForm({ name: "", address: "", brand: "", tmClass: "", businessType: "" }); }}>
                  Generate Another
                </Button>
              </div>
            </div>
          )}
        </div>
      </section>
    </Layout>
  );
};

export default DocumentGenerator;
