import { Helmet } from "react-helmet-async";

const Terms = () => (
  <>
    <Helmet>
      <title>Terms of Service | IP Protection India</title>
      <meta name="description" content="Terms of service for using IP Protection India website and tools." />
    </Helmet>
    <section className="py-20 md:py-28">
      <div className="container mx-auto max-w-3xl px-4">
        <h1 className="mb-8 font-serif text-4xl font-bold">Terms of Service</h1>
        <div className="prose prose-sm text-muted-foreground space-y-4">
          <p>
            By accessing and using this website, you accept and agree to be bound by the terms and provisions of this agreement.
          </p>
          <h2 className="font-serif text-xl font-bold text-foreground">Use of Website</h2>
          <p>
            This website is provided for informational and educational purposes related to intellectual property law in India. The tools and resources available are intended to assist users in understanding trademark, copyright, and patent processes.
          </p>
          <h2 className="font-serif text-xl font-bold text-foreground">AI-Generated Content</h2>
          <p>
            Documents and suggestions generated by our AI tools (Brand Name Generator, Objection Reply Generator, Document Generator, etc.) are for reference purposes only. They do not constitute legal advice and should be reviewed by a qualified legal professional before use in any official capacity.
          </p>
          <h2 className="font-serif text-xl font-bold text-foreground">Professional Services</h2>
          <p>
            Engagement for professional legal services is subject to a separate engagement agreement. Submission of forms or inquiries through this website does not automatically create an attorney-client relationship.
          </p>
          <h2 className="font-serif text-xl font-bold text-foreground">Intellectual Property</h2>
          <p>
            All content on this website, including text, graphics, logos, and tools, is the property of IP Protection India and Advocate Anuradha R. Kulkarni. Unauthorized reproduction or distribution is prohibited.
          </p>
          <h2 className="font-serif text-xl font-bold text-foreground">Limitation of Liability</h2>
          <p>
            We shall not be liable for any indirect, incidental, special, or consequential damages arising from the use of this website or its tools. Users rely on information and generated content at their own risk.
          </p>
          <h2 className="font-serif text-xl font-bold text-foreground">Governing Law</h2>
          <p>
            These terms are governed by the laws of India. Any disputes shall be subject to the exclusive jurisdiction of courts in Mumbai, Maharashtra.
          </p>
          <p className="text-xs mt-8">Last updated: {new Date().toLocaleDateString("en-IN", { year: "numeric", month: "long" })}</p>
        </div>
      </div>
    </section>
  </>
);

export default Terms;